name: "Update Bot"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'
      
jobs:
  update-data:
    name: Update bot
    runs-on: "macos-latest"
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v2
      - name: "Install Packages"
        run: |
          install.packages('pak')
          pak::pak("JBGruber/atr")
          install.packages('rex')
          install.packages('dplyr')
          install.packages('tidyr')
          install.packages('lubridate')
          install.packages('rvest')
          install.packages('stringr')
          install.packages('purrr')          
          install.packages('curl')       
          install.packages('jsonlite')  
          install.packages('websocket')   
          install.packages('processx')    
          install.packages('R6')   
          install.packages('later')   
          install.packages('promises')   
          install.packages('fastmap')   
          install.packages('rlang')   
        shell: Rscript {0}
      - name: "Bot - Run"
        run: Rscript 'bot.R'
        env:
          bsky_name: ${{ secrets.bsky_name }}
          bsky_pw: ${{ secrets.bsky_pw }}
          adam_telegram: ${{ secrets.ADAM_TELEGRAM }}
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bot Routine
